rails_app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homepage#index'

  post '/search', to: 'deals#search'
  resources :deals, only: [:index, :show]

end

rails_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails_app/app/models/deal.rb
class Deal < ApplicationRecord

  has_many :user_deals
  has_many :users, through: :user_deals

  validates :name, presence: true
  validates :price, presence: true
  validates :url, presence: true, uniqueness: true
end

rails_app/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_deals
  has_many :deals, through: :user_deals
end

rails_app/app/models/user_deal.rb
class UserDeal < ApplicationRecord

  belongs_to :user
  belongs_to :deal
end

rails_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

rails_app/app/controllers/deals_controller.rb
# frozen_string_literal: true

class DealsController < ApplicationController

  before_action :authenticate_user!

  def index
    @deals = current_user.deals
  end

  def search
    deal = BasicParser.new(params[:deal][:url]).parse
    if deal
      deal_from_db = Deal.where(name: deal.name)
      if deal_from_db.empty?
        deal[:scrape_interval] = 60
        deal.save!
        deal_id = deal.id
      else
        deal_id = deal_from_db.first.id
      end
      current_user.user_deals.create!(deal_id: deal_id)
    end
    redirect_to deals_url
  end

  def show
    @deal = Deal.find(params[:id])
    @adapter = GraphiteAdapter.new
    deal_identifier = @deal.name.parameterize
    filtered_data = filter_data(@adapter.get_metric_json("price_monitor_internal.deals.#{deal_identifier}.price"))
    labels, data = prepare_data_for_chart(filtered_data)

    @data = {
      labels:   labels,
      datasets: [
        {
          label:           @deal.name,
          backgroundColor: 'rgba(151,187,205,0.2)',
          borderColor:     'rgba(151,187,205,1)',
          data:            data,
        },
      ],
    }
    @options = { height: 200 }
  end

  private

  def filter_data(data)
    filtered = []
    data.each do |data|
      filtered.append(data) if data[0].present?
    end
    filtered
  end

  def prepare_data_for_chart(data)
    labels = []
    values = []
    data.each do |arr|
      values.append(arr[0])
      labels.append("#{Time.at(arr[1]).strftime('%Y-%m-%d')} #{Time.at(arr[1]).strftime('%H:%M')}")
    end
    [labels, values]
  end

end

rails_app/app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index; end
end

rails_app/app/helpers/application_helper.rb
module ApplicationHelper
end

rails_app/app/helpers/deals_helper.rb
module DealsHelper
  def cut_provider_name(name)
    name[4...name.length]
  end
end

rails_app/app/helpers/homepage_helper.rb
module HomepageHelper
end

rails_app/app/views/deals/_search.html.haml
= form_for Deal.new, url: search_path, method: :post do |f|
  .input-group.search
    = f.text_field :url, class: 'form-control', placeholder: 'https://www.itaka.pl'
    %span.input-group-btn
      = f.button('Search', class: 'btn btn-default')

rails_app/app/views/deals/index.html.haml
.well
  - @deals.each do |deal|
    .deal
      .names
        %h5= deal.name
        %h5= cut_provider_name(deal.provider)
      .price
        %h3= deal.price
      .button
        =link_to 'See more', deal_path(deal), class: 'btn btn-default'

rails_app/app/views/deals/show.html.haml
.well
  =chartjs_line_chart @data, @options

rails_app/app/views/homepage/index.html.haml
.well
  - if current_user
    = image_tag 'phone1.gif'
    .header
      %h1 Paste url to track!
      = render 'deals/search'
  - else
    .header
      %h1 Welcome to
      %h1 PRICE MONITOR
      %h1 as a service
    .banner
      = image_tag 'logos1.gif'
    .section
      %h3 Don't waste any of Your precious time for checking price again, let us do it for You!
      .privilege
        %h2 Joining price monitor lets you:
        %ul
          .list-items
            %li
              %h4 track your desired DEAL
            %li
              %h4 receive ALERTS about price change
            %li
              %h4 VISUALIZE price change. Easily and Beautifully.
      %h2 Feel like talking? Contact us!
    .banner
      = image_tag 'cards.png'

rails_app/app/views/layouts/_footer.html.haml
%footer.footer

rails_app/app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  %nav.navbar.navbar-inverse.navbar-fixed-top{role: 'navigation'}
    %div.nav-container
      %div.navbar-header
        %button.navbar-toggle{'data-target' => '#bs-example-navbar-collapse-1', 'data-toggle'=> 'collapse', type: 'button'}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        = image_tag 'small_logo.png'
        = link_to 'Price monitor', root_url, class: 'navbar-brand'
      %div.collapse.navbar-collapse.navbar-right#bs-example-navbar-collapse-1
        %ul.nav.navbar-nav
          - if current_user
            %li
              = link_to 'My trackings', deals_path
            %li.dropdown
              %a.dropdown-toggle{'href' => '#', 'data-toggle' => 'dropdown'}
                Account
                %b.caret
              %ul.dropdown-menu
                %li
                  = link_to 'Profile', '#'
                %li
                  = link_to 'Settings', '#'
                %li.divider
                %li
                  = link_to 'Log out', destroy_user_session_path, method: :delete
          - else
            %li
              = link_to 'Log in', new_user_session_path
            %li
              = link_to 'Sign up', new_user_registration_path

rails_app/app/views/layouts/application.html.haml
%html
  %head
    %title
      Price monitor

    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    = render 'layouts/header'
    - flash.each do |message_type, message|
      .alert{ class: "alert-#{message_type}" }
        %button.close{ 'data-dismiss': 'alert' }
          %span{ 'aria-hidden': true }
            &times;
        = message.html_safe
    %div.container
      = yield
    = render 'layouts/footer'

rails_app/app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>